module.exports = [
  {
    key: 'user',
    name: 'User',
    icon: 'ion-ios-person-outline',
    child: [
      {
        key: 'addUser',
        name: 'Add User',
        link: '/dashboard/user/add-user',
      },
      {
        key: 'listUser',
        name: 'List User',
        link: '/dashboard/user/list-user',
      },
      // {
      //   key: 'userSettings',
      //   name: 'User Settings',
      //   link: '/dashboard/user/user-settings',
      // },
    ],
  },
  {
    key: 'gifts',
    name: 'Gifts',
    icon: 'ion-ios-ionitron-outline',
    child: [
      {
        key: 'addGifts',
        name: 'Add Gifts',
        link: '/dashboard/gifts/add-gifts',
      },
    ],
  },
  {
    key: 'banner',
    name: 'Banner',
    icon: 'ion-ios-card',
    child: [
      {
        key: 'addBanner',
        name: 'Add Banner',
        link: '/dashboard/banner/add-banner',
      },
    ],
  },
  {
    key: 'promotions',
    name: 'Promotions',
    icon: 'ion-ios-paper-plane',
    child: [
      {
        key: 'addPromotions',
        name: 'Add Promotions',
        link: '/dashboard/promotion/add-promotions',
      }
    ],
  },
  {
    key: 'broadcasts',
    name: 'Broadcasts',
    icon: 'ion-ios-videocam',
    child: [
      {
        key: 'listBroadcasts',
        name: 'List Broadcasts',
        link: '/dashboard/broadcasts/list-broadcast',
      }
    ],
  },
  // {
  //   key: 'home',
  //   name: 'Home',
  //   icon: 'ion-ios-home-outline',
  //   child: [
  //     {
  //       key: 'landing_page',
  //       name: 'Landing Page',
  //       title: true,
  //     },
  //     {
  //       key: 'corporate',
  //       name: 'Corporate',
  //       link: '/',
  //       badge: 'Hot',
  //       icon: 'ion-ios-globe-outline',
  //     },
  //     {
  //       key: 'creative',
  //       name: 'Creative',
  //       link: '/landing-creative',
  //       icon: 'ion-ios-desktop-outline',
  //     },
  //     {
  //       key: 'dashboard',
  //       name: 'Dashboard',
  //       title: true,
  //     },
  //     {
  //       key: 'personal',
  //       name: 'Personal',
  //       link: '/app',
  //       icon: 'ion-ios-contact-outline',
  //     },
  //     {
  //       key: 'crm',
  //       name: 'CRM',
  //       link: '/dashboard/crm-dashboard',
  //       icon: 'ion-ios-card-outline',
  //     },
  //     {
  //       key: 'crypto',
  //       name: 'Cryptocurrency',
  //       link: '/dashboard/crypto-dashboard',
  //       icon: 'ion-ios-medal-outline',
  //     },
  //     {
  //       key: 'dashboard_widgets',
  //       name: 'Dashboard Widgets',
  //       title: true,
  //     },
  //     {
  //       key: 'infographics_wdiget',
  //       name: 'Infographics',
  //       link: '/dashboard/widgets/infographics',
  //       icon: 'ion-ios-card',
  //     },
  //     {
  //       key: 'status_widget',
  //       name: 'Status',
  //       link: '/dashboard/widgets/status',
  //       icon: 'ion-ios-notifications-outline',
  //     },
  //     {
  //       key: 'mini_apps_widget',
  //       name: 'Mini Apps',
  //       link: '/dashboard/widgets/mini-apps',
  //       icon: 'ion-ios-information-circle-outline',
  //     },
  //     {
  //       key: 'analytics_widget',
  //       name: 'Analytics',
  //       link: '/dashboard/widgets/analytics',
  //       icon: 'ion-ios-analytics-outline',
  //     },
  //     {
  //       key: 'info_updates_widget',
  //       name: 'Info & Updates',
  //       link: '/dashboard/widgets/info-updates',
  //       icon: 'ion-ios-information-circle-outline',
  //     },
  //     {
  //       key: 'layout_settings',
  //       name: 'Layout',
  //       title: true,
  //     },
  //     {
  //       key: 'grid',
  //       name: 'Grid',
  //       link: '/dashboard/layouts/grid',
  //       icon: 'ion-ios-apps-outline',
  //     },
  //     {
  //       key: 'application_layout',
  //       name: 'App Layout',
  //       link: '/dashboard/layouts/app-layout',
  //       icon: 'ion-ios-photos-outline',
  //     },
  //     {
  //       key: 'responsive',
  //       name: 'Responsive',
  //       link: '/dashboard/layouts/responsive',
  //       icon: 'ion-ios-phone-portrait',
  //     },
  //   ],
  // },
  // {
  //   key: 'home',
  //   name: 'Home',
  //   icon: 'ion-ios-home-outline',
  //   key: 'apps',
  //   name: 'Applications',
  //   icon: 'ion-ios-appstore-outline',
  //   child: [
  //     {
  //       key: 'communication_apps',
  //       name: 'Communication',
  //       title: true,
  //     },
  //     {
  //       key: 'contact',
  //       name: 'Contact',
  //       link: '/dashboard/pages/contact',
  //       icon: 'ion-ios-contact-outline',
  //     },
  //     {
  //       key: 'email',
  //       name: 'Email',
  //       link: '/dashboard/pages/email',
  //       badge: '2',
  //       icon: 'ion-ios-mail-outline',
  //     },
  //     {
  //       key: 'social_apps',
  //       name: 'Social',
  //       title: true,
  //     },
  //     {
  //       key: 'personal',
  //       name: 'Personal',
  //       link: '/app',
  //       icon: 'ion-ios-contact-outline',
  //     },
  //     {
  //       key: 'timeline',
  //       name: 'Timeline',
  //       link: '/dashboard/pages/timeline',
  //       icon: 'ion-ios-people-outline',
  //     },
  //     {
  //       key: 'chat',
  //       name: 'Chat',
  //       link: '/dashboard/pages/chat',
  //       badge: '4',
  //       icon: 'ion-ios-chatbubbles-outline',
  //     },
  //     {
  //       key: 'ecommerce_app',
  //       name: 'Ecommerce',
  //       title: true,
  //     },
  //     {
  //       key: 'Itemlist',
  //       name: 'Product Catalogues',
  //       link: '/dashboard/pages/ecommerce',
  //       icon: 'ion-ios-apps-outline',
  //     },
  //     {
  //       key: 'item_detail',
  //       name: 'Product Detail',
  //       link: '/dashboard/pages/product-detail',
  //       icon: 'ion-ios-card',
  //     },
  //     {
  //       key: 'checkout',
  //       name: 'Checkout Page',
  //       link: '/dashboard/pages/checkout',
  //       icon: 'ion-ios-cart-outline',
  //     },
  //     {
  //       key: 'dynamic_invoice',
  //       name: 'Dynamic Invoice',
  //       link: '/dashboard/pages/invoice',
  //       icon: 'ion-ios-document-outline',
  //     },
  //     {
  //       key: 'productivity_app',
  //       name: 'Productivity',
  //       title: true,
  //     },
  //     {
  //       key: 'calendar',
  //       name: 'Calendar',
  //       link: '/dashboard/pages/calendar',
  //       icon: 'ion-ios-calendar-outline',
  //     },
  //     {
  //       key: 'task',
  //       name: 'Task Board',
  //       link: '/dashboard/pages/taskboard',
  //       icon: 'ion-ios-checkmark-circle-outline',
  //     },
  //   ],
  // },
  // {
  //   key: 'pages',
  //   name: 'Pages',
  //   icon: 'ion-ios-paper-outline',
  //   child: [
  //     {
  //       key: 'account_page',
  //       name: 'Auth Page',
  //       title: true,
  //     },
  //     {
  //       key: 'login',
  //       name: 'Login',
  //       link: '/login',
  //       icon: 'ion-ios-person-outline',
  //     },
  //     {
  //       key: 'login2',
  //       name: 'Login Ver.2',
  //       link: '/login-v2',
  //       icon: 'ion-ios-contact-outline',
  //     },
  //     {
  //       key: 'login3',
  //       name: 'Login Ver.3',
  //       link: '/login-v3',
  //       icon: 'ion-ios-contact-outline',
  //     },
  //     {
  //       key: 'register',
  //       name: 'Register',
  //       link: '/register',
  //       icon: 'ion-ios-key-outline',
  //     },
  //     {
  //       key: 'register2',
  //       name: 'Register Ver.2',
  //       link: '/register-v2',
  //       icon: 'ion-ios-key-outline',
  //     },
  //     {
  //       key: 'register3',
  //       name: 'Register Ver.3',
  //       link: '/register-v3',
  //       icon: 'ion-ios-key-outline',
  //     },
  //     {
  //       key: 'reset',
  //       name: 'Reset Password',
  //       link: '/reset-password',
  //       icon: 'ion-ios-undo-outline',
  //     },
  //     {
  //       key: 'lock',
  //       name: 'Lock Screen',
  //       link: '/lock-screen',
  //       icon: 'ion-ios-lock-outline',
  //     },
  //     {
  //       key: 'generic_page',
  //       name: 'General',
  //       title: true,
  //     },
  //     {
  //       key: 'user_profile',
  //       name: 'User Profile',
  //       link: '/dashboard/pages/user-profile',
  //       icon: 'ion-ios-person-outline',
  //     },
  //     {
  //       key: 'blank',
  //       name: 'Blank Page',
  //       link: '/dashboard/pages/blank-page',
  //       icon: 'ion-ios-document-outline',
  //     },
  //     {
  //       key: 'pricing',
  //       name: 'Pricing Page',
  //       link: '/dashboard/pages/pricing',
  //       icon: 'ion-ios-archive-outline',
  //     },
  //     {
  //       key: 'gallery',
  //       name: 'Photo Gallery',
  //       link: '/dashboard/pages/photo-gallery',
  //       icon: 'ion-ios-images-outline',
  //     },
  //     {
  //       key: 'settings',
  //       name: 'Settings',
  //       link: '/dashboard/pages/settings',
  //       icon: 'ion-ios-options-outline',
  //     },
  //     {
  //       key: 'help_support',
  //       name: 'Help & Support',
  //       link: '/dashboard/pages/help-support',
  //       icon: 'ion-ios-help-circle-outline',
  //     },
  //     {
  //       key: 'maintenance',
  //       name: 'Maintenance',
  //       link: '/maintenance',
  //       icon: 'ion-ios-build-outline',
  //     },
  //     {
  //       key: 'coming_soon',
  //       name: 'Coming Soon',
  //       link: '/coming-soon',
  //       icon: 'ion-ios-bonfire-outline',
  //     },
  //     {
  //       key: 'blog',
  //       name: 'Blog',
  //       title: true,
  //     },
  //     {
  //       key: 'blog_list',
  //       name: 'Blog Home',
  //       link: '/blog',
  //       icon: 'ion-ios-home-outline',
  //     },
  //     {
  //       key: 'blog_detail',
  //       name: 'Article',
  //       link: '/blog/article',
  //       icon: 'ion-ios-list-box-outline',
  //     },
  //     {
  //       key: 'errors',
  //       name: 'Errors',
  //       title: true,
  //     },
  //     {
  //       key: 'not_found_page',
  //       name: 'Not Found Page',
  //       link: '/dashboard/pages/not-found',
  //       icon: 'ion-ios-warning-outline',
  //     },
  //     {
  //       key: 'error_page',
  //       name: 'Error Page',
  //       link: '/dashboard/pages/error',
  //       icon: 'ion-ios-warning-outline',
  //     },
  //   ],
  // },
  // {
  //   key: 'tables',
  //   name: 'Tables',
  //   icon: 'ion-ios-grid-outline',
  //   child: [
  //     {
  //       key: 'common_table',
  //       name: 'Common Table',
  //       title: true,
  //     },
  //     {
  //       key: 'basic_table',
  //       name: 'Basic',
  //       link: '/dashboard/tables/basic-table',
  //       icon: 'ion-ios-grid-outline',
  //     },
  //     {
  //       key: 'data_table',
  //       name: 'Data Tables',
  //       link: '/dashboard/tables/data-table',
  //       icon: 'ion-ios-cube-outline',
  //     },
  //     {
  //       key: 'table_playground',
  //       name: 'Table Playgound',
  //       link: '/dashboard/tables/table-playground',
  //       icon: 'ion-ios-list-box-outline',
  //     },
  //     {
  //       key: 'redux_table',
  //       name: 'Redux Table',
  //       title: true,
  //     },
  //     {
  //       key: 'editable_cell',
  //       name: 'Table Edit',
  //       link: '/dashboard/tables/editable-cell',
  //       icon: 'ion-ios-cube-outline',
  //     },
  //     {
  //       key: 'tree_table',
  //       name: 'Tree Table',
  //       link: '/dashboard/tables/tree-table',
  //       icon: 'ion-ios-git-merge',
  //     },
  //   ],
  // },
  // {
  //   key: 'forms',
  //   name: 'Forms Buttons',
  //   icon: 'ion-ios-list-box-outline',
  //   child: [
  //     {
  //       key: 'buttons_collections',
  //       name: 'Button Collections',
  //       title: true,
  //     },
  //     {
  //       key: 'buttons',
  //       name: 'Buttons',
  //       link: '/dashboard/forms/buttons',
  //       icon: 'ion-ios-game-controller-a-outline',
  //     },
  //     {
  //       key: 'toggle_button',
  //       name: 'Toggle Button',
  //       link: '/dashboard/forms/toggle-button',
  //       icon: 'ion-ios-switch-outline',
  //     },
  //     {
  //       key: 'dial_button',
  //       name: 'Dial Button',
  //       link: '/dashboard/forms/dial-button',
  //       icon: 'ion-ios-add-circle-outline',
  //     },
  //     {
  //       key: 'text_input',
  //       name: 'Text Input',
  //       title: true,
  //     },
  //     {
  //       key: 'textfields',
  //       name: 'Textfields',
  //       link: '/dashboard/forms/textfields',
  //       icon: 'ion-ios-list-box-outline',
  //     },
  //     {
  //       key: 'autocomplete',
  //       name: 'Autocomplete & Tag',
  //       link: '/dashboard/forms/autocomplete',
  //       icon: 'ion-ios-list',
  //     },
  //     {
  //       key: 'datetimepicker',
  //       name: 'Date Time Picker',
  //       link: '/dashboard/forms/date-time-picker',
  //       icon: 'ion-ios-calendar-outline',
  //     },
  //     {
  //       key: 'reduxform',
  //       name: 'Redux Form',
  //       link: '/dashboard/forms/reduxform',
  //       icon: 'ion-ios-list-box-outline',
  //     },
  //     {
  //       key: 'selection',
  //       name: 'Selection',
  //       title: true,
  //     },
  //     {
  //       key: 'checkbox_radio',
  //       name: 'Checkbox & Radio',
  //       link: '/dashboard/forms/checkbox-radio',
  //       icon: 'ion-ios-checkbox-outline',
  //     },
  //     {
  //       key: 'switches',
  //       name: 'Switches',
  //       link: '/dashboard/forms/switches',
  //       icon: 'ion-ios-switch-outline',
  //     },
  //     {
  //       key: 'selectbox',
  //       name: 'Select',
  //       link: '/dashboard/forms/selectbox',
  //       icon: 'ion-ios-menu-outline',
  //     },
  //     {
  //       key: 'advanced_input',
  //       name: 'Advanced Input',
  //       title: true,
  //     },
  //     {
  //       key: 'slider',
  //       name: 'Slider Range',
  //       link: '/dashboard/forms/slider-range',
  //       icon: 'ion-ios-options-outline',
  //     },
  //     {
  //       key: 'upload',
  //       name: 'Upload',
  //       link: '/dashboard/forms/upload',
  //       icon: 'ion-ios-cloud-upload-outline',
  //     },
  //     {
  //       key: 'ratting',
  //       name: 'Ratting',
  //       link: '/dashboard/forms/ratting',
  //       icon: 'ion-ios-star-half',
  //     },
  //     {
  //       key: 'texteditor',
  //       name: 'WYSIWYG Editor',
  //       link: '/dashboard/forms/wysiwyg-editor',
  //       icon: 'ion-ios-create-outline',
  //     },
  //   ],
  // },
  // {
  //   key: 'ui',
  //   name: 'UI Collection',
  //   icon: 'ion-ios-flower-outline',
  //   child: [
  //     {
  //       key: 'material_content',
  //       name: 'Block Container',
  //       title: true,
  //     },
  //     {
  //       key: 'card_papper',
  //       name: 'Card & Papper',
  //       link: '/dashboard/ui/card-papper',
  //       icon: 'ion-ios-card-outline',
  //     },
  //     {
  //       key: 'accordion',
  //       name: 'Accordion',
  //       link: '/dashboard/ui/accordion',
  //       icon: 'ion-ios-menu-outline',
  //     },
  //     {
  //       key: 'material_navigation',
  //       name: 'Navigation',
  //       title: true,
  //     },
  //     {
  //       key: 'tab',
  //       name: 'Tabs Navigation',
  //       link: '/dashboard/ui/tabs',
  //       icon: 'ion-ios-folder-outline',
  //     },
  //     {
  //       key: 'drawer_menu',
  //       name: 'Menu & Drawer',
  //       link: '/dashboard/ui/drawer-menu',
  //       icon: 'ion-ios-settings-outline',
  //     },
  //     {
  //       key: 'breadcrumbs',
  //       name: 'Breadcrumbs',
  //       link: '/dashboard/ui/breadcrumbs',
  //       icon: 'ion-ios-arrow-dropright',
  //     },
  //     {
  //       key: 'paginations',
  //       name: 'Paginations',
  //       link: '/dashboard/ui/paginations',
  //       icon: 'ion-ios-arrow-round-forward',
  //     },
  //     {
  //       key: 'steppers',
  //       name: 'Steppers',
  //       link: '/dashboard/ui/steppers',
  //       icon: 'ion-ios-glasses-outline',
  //     },
  //     {
  //       key: 'material_popup',
  //       name: 'Popup',
  //       title: true,
  //     },
  //     {
  //       key: 'dialog_modal',
  //       name: 'Dialog & Modal',
  //       link: '/dashboard/ui/dialog-modal',
  //       icon: 'ion-ios-glasses-outline',
  //     },
  //     {
  //       key: 'popover_tooltip',
  //       name: 'Popover & Tooltip',
  //       link: '/dashboard/ui/popover-tooltip',
  //       icon: 'ion-ios-photos-outline',
  //     },
  //     {
  //       key: 'material_notif',
  //       name: 'Notification',
  //       title: true,
  //       icon: 'ion-ios-information-circle-outline',
  //     },
  //     {
  //       key: 'badges',
  //       name: 'Badges',
  //       link: '/dashboard/ui/badges',
  //       icon: 'ion-ios-bookmark-outline',
  //     },
  //     {
  //       key: 'snackbar',
  //       name: 'Messages',
  //       link: '/dashboard/ui/snackbar',
  //       icon: 'ion-ios-notifications-outline',
  //     },
  //     {
  //       key: 'material_dividers',
  //       name: 'Dividers',
  //       title: true,
  //     },
  //     {
  //       key: 'list_divider',
  //       name: 'List & Divider',
  //       link: '/dashboard/ui/list',
  //       icon: 'ion-ios-menu',
  //     },
  //     {
  //       key: 'custom_dividers',
  //       name: 'Custom Dividers',
  //       link: '/dashboard/ui/dividers',
  //       icon: 'ion-ios-menu-outline',
  //     },
  //     {
  //       key: 'material_image',
  //       name: 'Images',
  //       title: true,
  //     },
  //     {
  //       key: 'avatars',
  //       name: 'Avatars',
  //       link: '/dashboard/ui/avatars',
  //       icon: 'ion-ios-contact-outline',
  //     },
  //     {
  //       key: 'image_gird',
  //       name: 'Image Grid Gallery',
  //       link: '/dashboard/ui/image-grid',
  //       icon: 'ion-ios-apps-outline',
  //     },
  //     {
  //       key: 'slider_carousel',
  //       name: 'Slider & Carousel',
  //       link: '/dashboard/ui/slider-carousel',
  //       icon: 'ion-ios-images-outline',
  //     },
  //     {
  //       key: 'material_font_icon',
  //       name: 'Fonts & Icons',
  //       title: true,
  //     },
  //     {
  //       key: 'typography',
  //       name: 'Typography',
  //       link: '/dashboard/ui/typography',
  //       icon: 'ion-ios-create-outline',
  //     },
  //     {
  //       key: 'icons',
  //       name: 'Material Icons',
  //       link: '/dashboard/ui/icons',
  //       icon: 'ion-ios-heart-outline',
  //     },
  //     {
  //       key: 'ionicons',
  //       name: 'Ion Icons',
  //       link: '/dashboard/ui/ionicons',
  //       icon: 'ion-ios-ionic-outline',
  //     },
  //     {
  //       key: 'utilities',
  //       name: 'Utility',
  //       title: true,
  //     },
  //     {
  //       key: 'progress',
  //       name: 'Progress & Spinners',
  //       link: '/dashboard/ui/progress',
  //       icon: 'ion-ios-glasses-outline',
  //     },
  //     {
  //       key: 'tags',
  //       name: 'Tags',
  //       link: '/dashboard/ui/tags',
  //       icon: 'ion-ios-pricetag-outline',
  //     },
  //   ],
  // },
  // {
  //   key: 'charts',
  //   name: 'Charts',
  //   icon: 'ion-ios-pie-outline',
  //   child: [
  //     {
  //       key: 'svg_chart',
  //       name: 'SVG Chart',
  //       title: true,
  //     },
  //     {
  //       key: 'line_charts',
  //       name: 'Line',
  //       link: '/dashboard/charts/line-charts',
  //       icon: 'ion-ios-pulse-outline',
  //     },
  //     {
  //       key: 'bar_charts',
  //       name: 'Bar',
  //       link: '/dashboard/charts/bar-charts',
  //       icon: 'ion-ios-stats-outline',
  //     },
  //     {
  //       key: 'area_charts',
  //       name: 'Area',
  //       link: '/dashboard/charts/area-charts',
  //       icon: 'ion-ios-analytics-outline',
  //     },
  //     {
  //       key: 'pie_charts',
  //       name: 'Pie & Doughnut',
  //       link: '/dashboard/charts/pie-charts',
  //       icon: 'ion-ios-pie-outline',
  //     },
  //     {
  //       key: 'radar_charts',
  //       name: 'Radar',
  //       link: '/dashboard/charts/radar-charts',
  //       icon: 'ion-ios-ionic-outline',
  //     },
  //     {
  //       key: 'scatter_charts',
  //       name: 'Scatter',
  //       link: '/dashboard/charts/scatter-charts',
  //       icon: 'ion-ios-sunny-outline',
  //     },
  //     {
  //       key: 'compossed_charts',
  //       name: 'Compossed',
  //       link: '/dashboard/charts/compossed-chart',
  //       icon: 'ion-ios-stats-outline',
  //     },
  //     {
  //       key: 'canvas_chart',
  //       name: 'Canvas Chart',
  //       title: true,
  //     },
  //     {
  //       key: 'doughnut_pie',
  //       name: 'Doughnut & Pie',
  //       link: '/dashboard/charts/doughnut-pie-charts',
  //       icon: 'ion-ios-pie-outline',
  //     },
  //     {
  //       key: 'bar_canvas_chart',
  //       name: 'Bar Direction',
  //       link: '/dashboard/charts/bar-direction-charts',
  //       icon: 'ion-ios-stats-outline',
  //     },
  //     {
  //       key: 'line_canvas_chart',
  //       name: 'Line and Scatter',
  //       link: '/dashboard/charts/line-scatter-charts',
  //       icon: 'ion-ios-sunny-outline',
  //     },
  //     {
  //       key: 'area_canvas_chart',
  //       name: 'Area Filled',
  //       link: '/dashboard/charts/area-filled-charts',
  //       icon: 'ion-ios-analytics-outline',
  //     },
  //     {
  //       key: 'radar_canvas_chart',
  //       name: 'Radar and Polar',
  //       link: '/dashboard/charts/radar-polar-chart',
  //       icon: 'ion-ios-ionic-outline',
  //     },
  //   ],
  // },
  // {
  //   key: 'maps',
  //   name: 'Maps',
  //   icon: 'ion-ios-navigate-outline',
  //   child: [
  //     {
  //       key: 'google_map',
  //       name: 'Google Map',
  //       title: true,
  //     },
  //     {
  //       key: 'map_marker',
  //       name: 'Map Marker',
  //       link: '/dashboard/maps/map-marker',
  //       icon: 'ion-ios-pin-outline',
  //     },
  //     {
  //       key: 'map_direction',
  //       name: 'Map Direction',
  //       link: '/dashboard/maps/map-direction',
  //       icon: 'ion-ios-arrow-dropright',
  //     },
  //     {
  //       key: 'map_searchbox',
  //       name: 'Map with Searchbox',
  //       link: '/dashboard/maps/map-searchbox',
  //       icon: 'ion-ios-search-outline',
  //     },
  //     {
  //       key: 'map_traffic',
  //       name: 'Traffic Indicator',
  //       link: '/dashboard/maps/map-traffic',
  //       icon: 'ion-ios-car-outline',
  //     },
  //     {
  //       key: 'street_view',
  //       name: 'Street View',
  //       link: '/dashboard/maps/street-view',
  //       icon: 'ion-ios-eye-outline',
  //     },
  //   ],
  // },
  // {
  //   key: 'menu_levels',
  //   name: 'Menu Levels',
  //   multilevel: true,
  //   icon: 'ion-ios-menu-outline',
  //   child: [
  //     {
  //       key: 'level_1',
  //       name: 'Level 1',
  //       link: '/#',
  //     },
  //     {
  //       key: 'level_2',
  //       keyParent: 'menu_levels',
  //       name: 'Level 2',
  //       child: [
  //         {
  //           key: 'sub_menu_1',
  //           name: 'Sub Menu 1',
  //           link: '/#',
  //         },
  //         {
  //           key: 'sub_menu_2',
  //           name: 'Sub Menu 2',
  //           link: '/#',
  //         },
  //       ],
  //     },
  //   ],
  // },
  {
    key: 'no_child',
    name: 'One Level Menu',
    icon: 'ion-ios-document-outline',
    linkParent: '/dashboard/pages/blank-page',
  },
];
